# Generated by Django 3.0.4 on 2020-03-21 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuckcovid_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('surname', models.CharField(max_length=255, verbose_name='apellidos')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='empresa')),
                ('address', models.TextField(blank=True, null=True, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='localidad')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='localidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
