# Generated by Django 3.0.4 on 2020-03-20 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0005_auto_20200320_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='localidad')),
                ('phone', models.CharField(max_length=15, verbose_name='teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Region', verbose_name='región')),
            ],
            options={
                'verbose_name': 'maker',
                'verbose_name_plural': 'makers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_day', models.PositiveIntegerField(default=0, verbose_name='capacidad por día')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('donation', models.BooleanField(default=False, verbose_name='donación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.Maker', verbose_name='maker')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'producción',
                'verbose_name_plural': 'producciones',
                'ordering': ['resource__name'],
            },
        ),
    ]
