# Generated by Django 3.0.4 on 2020-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200318_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='localidad'),
        ),
    ]
