# Generated by Django 3.0.4 on 2020-03-18 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0003_hospital_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='editor',
        ),
        migrations.AddField(
            model_name='need',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='alta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado'),
        ),
    ]
