# Generated by Django 3.0.4 on 2020-03-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200318_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitales'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
